env:
  mocha: true
  browser: true
  node: true
  es6: true
  mongo: true

extends:
  - eslint:recommended
  - plugin:promise/recommended
  - plugin:vue/recommended
  - airbnb-base

plugins:
  - import
  - promise
  - vue
  - html

parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    impliedStrict: true
