env:
  mocha: true
  browser: true
  node: true
  es6: true
  mongo: true

extends:
  - eslint:recommended
  - plugin:promise/recommended
  - airbnb-base

plugins:
  - import
  - promise
  - html

parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    impliedStrict: true

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - '**/*.test.js'
      - '**/*.spec.js'
