env:
  mocha: true
  browser: true
  node: true
  es6: true
  mongo: true

extends:
  - eslint:recommended
  - plugin:promise/recommended
  - airbnb-base

plugins:
  - import
  - promise

parserOptions:
  sourceType: script
