mongoose:
  url: 'mongodb://localhost:27017/express-starter'
  url_test: 'mongodb://localhost:27017/express-starter-test'
  connectOptions:
    keepAlive: 120
    connectTimeoutMS: 10000
    socketTimeoutMS: 10000
    poolSize: 10
    autoIndex: true
    w: majority
    wtimeout: 10000
    j: true
    reconnectTries: .inf
  schemaOptions:
    timestamps: true
    emitIndexErrors: true
    id: false
    minimize: false
    strict: true
    useNestedStrict: true
    retainKeyOrder: true
    toObject: &toObjectOptions
      getters: true
    toJSON:
      << : *toObjectOptions
    runSettersOnQuery: true

general:
  name: es
  protocol: 'http:' # must have :
  domain: 'localhost'
  port: 9999
  pathname: '/'
  search: ''
  hash: ''
  uploadPath: './public/images/uploads/' # TODO: use absolute path
  logPath: '../log/'

env:
  username:
    min: 3
    max: 50
  jwt:
    secret: 'secret'
    exp: '7d'
  birthyear:
    min: 0
    max: 2300

constant:
  Result:
    SUCCESS: success
    FAIL: fail
    ERROR: error
  Role:
    GUEST: guest
    MEMBER: member
    ADMIN: admin
