commonSocketOpts: &commonSocketOpts
  keepAlive: 120
  connectTimeoutMS: 10000
  socketTimeoutMS: 10000
commonConnOpts: &commonConnOpts
  poolSize: 10

mongoose:
  url: 'mongodb://localhost:27017/vue-starter-kit'
  connectOptions:
    config:
      autoIndex: true
    db:
      w: majority
      wtimeout: 10000
      j: true
    server:
      << : *commonConnOpts
      reconnectTries: .inf
      socketOptions:
        << : *commonSocketOpts
    replset:
      << : *commonConnOpts
      socketOptions:
        << : *commonSocketOpts
  schemaOptions:
    timestamps: true
    emitIndexErrors: true
    id: false
    minimize: false
    strict: true
    useNestedStrict: true
    retainKeyOrder: true
    toObject: &toObjectOptions
      getters: true
    toJSON:
      << : *toObjectOptions
    runSettersOnQuery: true

general:
  protocol: 'http:' # must have :
  domain: 'localhost'
  port: 9999
  pathname: '/'
  search: ''
  hash: ''

env:
  username:
    min: 3
    max: 50
  jwt:
    secret: 'secret'
    exp: '7d'

constant:
  Result:
    SUCCESS: success
    FAIL: fail
    ERROR: error
